INSERT INTO employee (name, age) VALUES ('Mark Zuckerberg', 31);
INSERT INTO employee (name, age) VALUES ('Sergey Brin', 42);
INSERT INTO employee (name, age) VALUES ('Kent Beck', 54);
INSERT INTO employee (name, age) VALUES ('Tim Berners Lee', 60);
INSERT INTO employee (name, age) VALUES ('Joshua Bloch', 54);
INSERT INTO employee (name, age) VALUES ('James Gosling', 60);
INSERT INTO employee (name, age) VALUES ('Martin Odersky', 57);
INSERT INTO employee (name, age) VALUES ('Dennis Ritchie (deceased)', 70);
INSERT INTO employee (name, age) VALUES ('Aaron Swartz (deceased)', 26);
INSERT INTO employee (name, age) VALUES ('Joel Spolsky', 50);